# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import todo_pb2 as todo__pb2


class TodoGatewayStub(object):
  """ルーティング
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TodoCreate = channel.unary_unary(
        '/todo.TodoGateway/TodoCreate',
        request_serializer=todo__pb2.TodoCreateRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoCreateResponse.FromString,
        )
    self.TodoShow = channel.unary_unary(
        '/todo.TodoGateway/TodoShow',
        request_serializer=todo__pb2.TodoShowRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoShowResponse.FromString,
        )
    self.TodoUpdate = channel.unary_unary(
        '/todo.TodoGateway/TodoUpdate',
        request_serializer=todo__pb2.TodoUpdateRequest.SerializeToString,
        response_deserializer=todo__pb2.TodoUpdateResponse.FromString,
        )


class TodoGatewayServicer(object):
  """ルーティング
  """

  def TodoCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TodoShow(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TodoUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TodoGatewayServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TodoCreate': grpc.unary_unary_rpc_method_handler(
          servicer.TodoCreate,
          request_deserializer=todo__pb2.TodoCreateRequest.FromString,
          response_serializer=todo__pb2.TodoCreateResponse.SerializeToString,
      ),
      'TodoShow': grpc.unary_unary_rpc_method_handler(
          servicer.TodoShow,
          request_deserializer=todo__pb2.TodoShowRequest.FromString,
          response_serializer=todo__pb2.TodoShowResponse.SerializeToString,
      ),
      'TodoUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.TodoUpdate,
          request_deserializer=todo__pb2.TodoUpdateRequest.FromString,
          response_serializer=todo__pb2.TodoUpdateResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'todo.TodoGateway', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
