# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: todo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='todo.proto',
  package='todo',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\ntodo.proto\x12\x04todo\"3\n\rTodoComponent\x12\x11\n\ttodo_name\x18\x01 \x01(\t\x12\x0f\n\x07is_done\x18\x02 \x01(\x08\">\n\x17ServerResponseComponent\x12\x12\n\nis_success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x11TodoCreateRequest\x12\x11\n\ttodo_name\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"X\n\x12TodoCreateResponse\x12/\n\x08response\x18\x01 \x01(\x0b\x32\x1d.todo.ServerResponseComponent\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"$\n\x0fTodoShowRequest\x12\x11\n\ttimestamp\x18\x01 \x01(\t\"I\n\x10TodoShowResponse\x12\"\n\x05todos\x18\x01 \x03(\x0b\x32\x13.todo.TodoComponent\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"I\n\x11TodoUpdateRequest\x12!\n\x04todo\x18\x01 \x01(\x0b\x32\x13.todo.TodoComponent\x12\x11\n\ttimestamp\x18\x02 \x01(\t\"X\n\x12TodoUpdateResponse\x12/\n\x08response\x18\x01 \x01(\x0b\x32\x1d.todo.ServerResponseComponent\x12\x11\n\ttimestamp\x18\x02 \x01(\t2\xd0\x01\n\x0bTodoGateway\x12\x41\n\nTodoCreate\x12\x17.todo.TodoCreateRequest\x1a\x18.todo.TodoCreateResponse\"\x00\x12;\n\x08TodoShow\x12\x15.todo.TodoShowRequest\x1a\x16.todo.TodoShowResponse\"\x00\x12\x41\n\nTodoUpdate\x12\x17.todo.TodoUpdateRequest\x1a\x18.todo.TodoUpdateResponse\"\x00\x62\x06proto3'
)




_TODOCOMPONENT = _descriptor.Descriptor(
  name='TodoComponent',
  full_name='todo.TodoComponent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo_name', full_name='todo.TodoComponent.todo_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_done', full_name='todo.TodoComponent.is_done', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=71,
)


_SERVERRESPONSECOMPONENT = _descriptor.Descriptor(
  name='ServerResponseComponent',
  full_name='todo.ServerResponseComponent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_success', full_name='todo.ServerResponseComponent.is_success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='todo.ServerResponseComponent.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=135,
)


_TODOCREATEREQUEST = _descriptor.Descriptor(
  name='TodoCreateRequest',
  full_name='todo.TodoCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo_name', full_name='todo.TodoCreateRequest.todo_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='todo.TodoCreateRequest.timestamp', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=194,
)


_TODOCREATERESPONSE = _descriptor.Descriptor(
  name='TodoCreateResponse',
  full_name='todo.TodoCreateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='todo.TodoCreateResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='todo.TodoCreateResponse.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=284,
)


_TODOSHOWREQUEST = _descriptor.Descriptor(
  name='TodoShowRequest',
  full_name='todo.TodoShowRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='todo.TodoShowRequest.timestamp', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=322,
)


_TODOSHOWRESPONSE = _descriptor.Descriptor(
  name='TodoShowResponse',
  full_name='todo.TodoShowResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todos', full_name='todo.TodoShowResponse.todos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='todo.TodoShowResponse.timestamp', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=397,
)


_TODOUPDATEREQUEST = _descriptor.Descriptor(
  name='TodoUpdateRequest',
  full_name='todo.TodoUpdateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='todo', full_name='todo.TodoUpdateRequest.todo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='todo.TodoUpdateRequest.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=399,
  serialized_end=472,
)


_TODOUPDATERESPONSE = _descriptor.Descriptor(
  name='TodoUpdateResponse',
  full_name='todo.TodoUpdateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='todo.TodoUpdateResponse.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='todo.TodoUpdateResponse.timestamp', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=562,
)

_TODOCREATERESPONSE.fields_by_name['response'].message_type = _SERVERRESPONSECOMPONENT
_TODOSHOWRESPONSE.fields_by_name['todos'].message_type = _TODOCOMPONENT
_TODOUPDATEREQUEST.fields_by_name['todo'].message_type = _TODOCOMPONENT
_TODOUPDATERESPONSE.fields_by_name['response'].message_type = _SERVERRESPONSECOMPONENT
DESCRIPTOR.message_types_by_name['TodoComponent'] = _TODOCOMPONENT
DESCRIPTOR.message_types_by_name['ServerResponseComponent'] = _SERVERRESPONSECOMPONENT
DESCRIPTOR.message_types_by_name['TodoCreateRequest'] = _TODOCREATEREQUEST
DESCRIPTOR.message_types_by_name['TodoCreateResponse'] = _TODOCREATERESPONSE
DESCRIPTOR.message_types_by_name['TodoShowRequest'] = _TODOSHOWREQUEST
DESCRIPTOR.message_types_by_name['TodoShowResponse'] = _TODOSHOWRESPONSE
DESCRIPTOR.message_types_by_name['TodoUpdateRequest'] = _TODOUPDATEREQUEST
DESCRIPTOR.message_types_by_name['TodoUpdateResponse'] = _TODOUPDATERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TodoComponent = _reflection.GeneratedProtocolMessageType('TodoComponent', (_message.Message,), {
  'DESCRIPTOR' : _TODOCOMPONENT,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo.TodoComponent)
  })
_sym_db.RegisterMessage(TodoComponent)

ServerResponseComponent = _reflection.GeneratedProtocolMessageType('ServerResponseComponent', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSECOMPONENT,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo.ServerResponseComponent)
  })
_sym_db.RegisterMessage(ServerResponseComponent)

TodoCreateRequest = _reflection.GeneratedProtocolMessageType('TodoCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TODOCREATEREQUEST,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo.TodoCreateRequest)
  })
_sym_db.RegisterMessage(TodoCreateRequest)

TodoCreateResponse = _reflection.GeneratedProtocolMessageType('TodoCreateResponse', (_message.Message,), {
  'DESCRIPTOR' : _TODOCREATERESPONSE,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo.TodoCreateResponse)
  })
_sym_db.RegisterMessage(TodoCreateResponse)

TodoShowRequest = _reflection.GeneratedProtocolMessageType('TodoShowRequest', (_message.Message,), {
  'DESCRIPTOR' : _TODOSHOWREQUEST,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo.TodoShowRequest)
  })
_sym_db.RegisterMessage(TodoShowRequest)

TodoShowResponse = _reflection.GeneratedProtocolMessageType('TodoShowResponse', (_message.Message,), {
  'DESCRIPTOR' : _TODOSHOWRESPONSE,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo.TodoShowResponse)
  })
_sym_db.RegisterMessage(TodoShowResponse)

TodoUpdateRequest = _reflection.GeneratedProtocolMessageType('TodoUpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _TODOUPDATEREQUEST,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo.TodoUpdateRequest)
  })
_sym_db.RegisterMessage(TodoUpdateRequest)

TodoUpdateResponse = _reflection.GeneratedProtocolMessageType('TodoUpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _TODOUPDATERESPONSE,
  '__module__' : 'todo_pb2'
  # @@protoc_insertion_point(class_scope:todo.TodoUpdateResponse)
  })
_sym_db.RegisterMessage(TodoUpdateResponse)



_TODOGATEWAY = _descriptor.ServiceDescriptor(
  name='TodoGateway',
  full_name='todo.TodoGateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=565,
  serialized_end=773,
  methods=[
  _descriptor.MethodDescriptor(
    name='TodoCreate',
    full_name='todo.TodoGateway.TodoCreate',
    index=0,
    containing_service=None,
    input_type=_TODOCREATEREQUEST,
    output_type=_TODOCREATERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TodoShow',
    full_name='todo.TodoGateway.TodoShow',
    index=1,
    containing_service=None,
    input_type=_TODOSHOWREQUEST,
    output_type=_TODOSHOWRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='TodoUpdate',
    full_name='todo.TodoGateway.TodoUpdate',
    index=2,
    containing_service=None,
    input_type=_TODOUPDATEREQUEST,
    output_type=_TODOUPDATERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TODOGATEWAY)

DESCRIPTOR.services_by_name['TodoGateway'] = _TODOGATEWAY

# @@protoc_insertion_point(module_scope)
